name = "little-libraries"
main = "app/app.js"
compatibility_date = "2023-01-01"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "little-libraries"
database_id = "90206c15-730f-4fd6-b3bc-6f2590975148"
